# Generated by Django 5.2.4 on 2025-07-31 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chamber_type', models.CharField(choices=[('palata', 'Palata'), ('lux', 'Lux')], default='palata', max_length=10)),
                ('room', models.IntegerField(blank=True, null=True)),
                ('place', models.CharField(blank=True, choices=[('joy1', 'Joy1'), ('joy2', 'Joy2')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_slot', models.CharField(choices=[('joy1', 'Joy1'), ('joy2', 'Joy2')], max_length=10)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('job', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
                ('brought', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('price_nurse', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('med_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='room.medroom')),
            ],
        ),
    ]
