# Generated by Django 5.2.4 on 2025-07-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_full_room',
            field=models.BooleanField(default=False),
        ),
    ]
