# Generated by Django 5.2.4 on 2025-07-31 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_rename_prica_expenses_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
